title:              Stash Coding
email:              mustafa.zukic3@gmail.com
description:        Mobile and Web Developement Tutorials
author:             Zukic Mustafa
baseurl:            ""
url:                ""

# Social Profiles
github_username:    mzukic3
linkedin_username:  mustafa-zukic-242a22160

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
