title:              Zukic Mustafa
email:              mustafa.zukic3@gmail.com
description:        Hi there, my name is Mustafa and I'm an Android developer.
                    This is my personal website where I post blogs and stuff I do as developer. Feel free to contact me :)
author:             Zukic Mustafa
baseurl:            "/blog"
url:                "https://mzukic3.github.io"

# Social Profiles
github_username:    mzukic3
linkedin_username:  mustafa-zukic-242a22160

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
